name: Create Release and Update Repository

on:
  workflow_call:
    inputs:
      internal_name:
        type: string
        required: true
      solution_name:
        type: string
        required: true
      build_configuration:
        type: string
        required: true
      personal_plugin_repo:
        type: string
        required: true
      personal_plugin_repo_branch:
        type: string
        required: true
      plugin_folder:
        type: string
        required: true
      project_dir:
        type: string
        required: true
      platform:
        type: string
        required: true
        default: x64
    secrets:
      PAT:
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet Packages
        run: nuget restore ${{ inputs.solution_name }}.sln

      - name: Download Dalamud
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
          $target = "$env:AppData\XIVLauncher\addon\Hooks\dev\"
          New-Item -ItemType Directory -Force -Path $target | Out-Null
          Expand-Archive -Force latest.zip $target

      - name: Build
        run: msbuild ${{ inputs.solution_name }}.sln /p:Configuration=${{ inputs.build_configuration }} /p:Platform=${{ inputs.platform }}

      # NEW: Install and run the official packager
      - name: Install DalamudPackager
        shell: pwsh
        run: dotnet tool install -g DalamudPackager

      - name: Pack with DalamudPackager
        shell: pwsh
        run: |
          $out  = Join-Path "${{ inputs.project_dir }}" "bin/${{ inputs.build_configuration }}/${{ inputs.platform }}"
          $dest = Join-Path $out "${{ inputs.plugin_folder }}"
          New-Item -ItemType Directory -Force -Path $dest | Out-Null

          # Run the packager against the csproj
          & "$env:USERPROFILE\.dotnet\tools\DalamudPackager.exe" pack `
            -p "${{ inputs.project_dir }}/${{ inputs.project_dir }}.csproj" `
            -o $dest

          # Normalize: ensure latest.zip exists (some setups emit a versioned zip as well)
          if (-not (Test-Path (Join-Path $dest 'latest.zip'))) {
            $zip = Get-ChildItem -Path $dest -Filter *.zip | Select-Object -First 1
            if ($zip) { Copy-Item $zip.FullName (Join-Path $dest 'latest.zip') -Force }
          }

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ./${{ inputs.project_dir }}/bin/${{ inputs.build_configuration }}/${{ inputs.platform }}/${{ inputs.plugin_folder }}/*

  deploy:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout Plugin Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.personal_plugin_repo }}
          token: ${{ secrets.PAT }}
          ref: ${{ inputs.personal_plugin_repo_branch }}

      - name: Download Plugin Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: plugins/${{ inputs.internal_name }}

      # NEW: Normalize manifest name and set RepoUrl to the plugin-list repo
      - name: Normalize manifest and RepoUrl
        shell: pwsh
        run: |
          $dir = "plugins/${{ inputs.internal_name }}"
          $manifest = Join-Path $dir "${{ inputs.internal_name }}.json"
          if (-not (Test-Path $manifest)) {
            $found = Get-ChildItem -Path $dir -Filter *.json | Select-Object -First 1
            if ($found) { Copy-Item $found.FullName $manifest -Force }
          }
          $json = Get-Content -Raw -Path $manifest | ConvertFrom-Json
          $json.RepoUrl = "https://github.com/${{ inputs.personal_plugin_repo }}"
          $json | ConvertTo-Json -Depth 100 | Set-Content -Path $manifest -Encoding UTF8

      - name: Extract version from manifest
        id: version
        shell: pwsh
        run: |
          $manifestPath = "plugins/${{ inputs.internal_name }}/${{ inputs.internal_name }}.json"
          $json = Get-Content -Raw -Path $manifestPath | ConvertFrom-Json
          "VERSION=$($json.AssemblyVersion)" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

      - name: Commit manifest to plugin list repo
        uses: EndBug/add-and-commit@v9
        with:
          add: ./plugins/${{ inputs.internal_name }}/${{ inputs.internal_name }}.json
          author_name: GitHub Action
          author_email: github-actions[bot]@users.noreply.github.com
          message: ${{ inputs.internal_name }} v${{ env.VERSION }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: v${{ env.VERSION }}
          files: ./plugins/${{ inputs.internal_name }}/latest.zip
          draft: false
          prerelease: false
