name: Create Release and Update Repository

on:
  workflow_call:
    inputs:
      internal_name:
        type: string
        required: true
      solution_name:
        type: string
        required: true
      build_configuration:
        type: string
        required: true
      personal_plugin_repo:
        type: string
        required: true
      personal_plugin_repo_branch:
        type: string
        required: true
      plugin_folder:
        type: string
        required: true
      project_dir:
        type: string
        required: true
      platform:
        type: string
        required: true
        default: x64
    secrets:
      PAT:
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet Packages
        run: nuget restore ${{ inputs.solution_name }}.sln

      - name: Download Dalamud
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
          $target = "$env:AppData\XIVLauncher\addon\Hooks\dev\"
          New-Item -ItemType Directory -Force -Path $target | Out-Null
          Expand-Archive -Force latest.zip $target

      - name: Build
        run: msbuild ${{ inputs.solution_name }}.sln /p:Configuration=${{ inputs.build_configuration }} /p:Platform=${{ inputs.platform }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ./${{ inputs.project_dir }}/bin/${{ inputs.build_configuration }}/${{ inputs.platform }}/*

  deploy:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout Plugin Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.personal_plugin_repo }}
          token: ${{ secrets.PAT }}
          ref: ${{ inputs.personal_plugin_repo_branch }}

      - name: Download Plugin Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: plugins/${{ inputs.internal_name }}

      # Extract version from the packaged manifest (Orchestrion.json)
      - name: Extract version from manifest
        id: version
        shell: pwsh
        run: |
          $manifestPath = "plugins/${{ inputs.internal_name }}/${{ inputs.internal_name }}.json"
          $json = Get-Content -Raw -Path $manifestPath | ConvertFrom-Json
          "VERSION=$($json.AssemblyVersion)" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

      # Commit the manifest to the plugin list repo
      - name: Commit manifest to plugin list repo
        uses: EndBug/add-and-commit@v9
        with:
          add: ./plugins/${{ inputs.internal_name }}/${{ inputs.internal_name }}.json
          author_name: GitHub Action
          author_email: github-actions[bot]@users.noreply.github.com
          message: ${{ inputs.internal_name }} v${{ env.VERSION }}

      # Create release from the packaged zip
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: v${{ env.VERSION }}
          files: ./plugins/${{ inputs.internal_name }}/latest.zip
          draft: false
          prerelease: false
